import { Tab } from "@headlessui/react";
import Head from "next/head";
import Image from "next/image";
import { Fragment, useEffect, useState } from "react";
import { Layout } from "../components/layout/layout";

import { Navigation } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import {
  FlightSearchCard,
  HomePreviewCard,
  HotelPreviewCard,
  HotelSearchCard,
  TourPreviewCard,
  TourSearchCard,
} from "../components/ui/cards/home";
import { HotDealsCard } from "../components/ui/cards/hotdeals/hotdealscard";
// import { HotDealsCard } from "../components/ui/cards/hotdeals/HotDealsCard";
import { SectionTitle } from "../components/ui/typography/sectionTitle";
import { images } from "../lib/images";
import style from "../styles/Home.module.scss";

function Home() {
  const [domLoaded, setDomLoaded] = useState(false);

  useEffect(() => {
    setDomLoaded(true);
  }, []);

  return (
    <>
      <Head>
        <title>Siyaahat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={style.home}>
        <section className={style.hero_banner}>
          <div className="container position-relative">
            <Tab.Group>
              <Tab.List
                className={`d-flex gap-4 ${style.searchtab_nav} box-shadow`}
              >
                <Tab as={Fragment}>
                  {({ selected }) => (
                    <button
                      className={`${style.tab_btn} ${
                        selected ? style.selected : ""
                      }`}
                    >
                      <svg
                        width="18"
                        height="18"
                        viewBox="0 0 18 18"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M17.2033 0.574099C17.7933 1.1641 17.7933 2.1141 17.2033 2.6941L13.3133 6.5841L15.4333 15.7741L14.0233 17.1941L10.1433 9.7641L6.24331 13.6641L6.60331 16.1341L5.53331 17.1941L3.77331 14.0141L0.583313 12.2441L1.64331 11.1641L4.14331 11.5341L8.01331 7.6641L0.583313 3.7541L2.00331 2.3441L11.1933 4.4641L15.0833 0.574099C15.6433 -0.00590086 16.6433 -0.00590086 17.2033 0.574099Z"
                          fill={selected ? "#feb20e" : "#3A4856"}
                        />
                      </svg>
                      Flights
                    </button>
                  )}
                </Tab>
                <Tab as={Fragment}>
                  {({ selected }) => (
                    <button
                      className={`${style.tab_btn}  ${
                        selected ? style.selected : ""
                      }`}
                    >
                      <svg
                        width="21"
                        height="19"
                        viewBox="0 0 21 19"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M20.5833 18.6666H0.583313V16.6666H1.58331V1.66663C1.58331 1.40141 1.68867 1.14706 1.87621 0.959519C2.06374 0.771983 2.3181 0.666626 2.58331 0.666626H16.5833C16.8485 0.666626 17.1029 0.771983 17.2904 0.959519C17.478 1.14706 17.5833 1.40141 17.5833 1.66663V6.66663H19.5833V16.6666H20.5833V18.6666ZM15.5833 16.6666H17.5833V8.66663H11.5833V16.6666H13.5833V10.6666H15.5833V16.6666ZM15.5833 6.66663V2.66663H3.58331V16.6666H9.58331V6.66663H15.5833ZM5.58331 8.66663H7.58331V10.6666H5.58331V8.66663ZM5.58331 12.6666H7.58331V14.6666H5.58331V12.6666ZM5.58331 4.66663H7.58331V6.66663H5.58331V4.66663Z"
                          fill={selected ? "#feb20e" : "#3A4856"}
                        />
                      </svg>{" "}
                      Hotels
                    </button>
                  )}
                </Tab>
                <Tab as={Fragment}>
                  {({ selected }) => (
                    <button
                      className={`${style.tab_btn}  ${
                        selected ? style.selected : ""
                      }`}
                    >
                      <svg
                        width="19"
                        height="20"
                        viewBox="0 0 19 20"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M16.3218 5.56506C17.7755 5.56506 18.9586 4.38225 18.9586 2.92819C18.9586 1.47413 17.7755 0.291626 16.3218 0.291626C14.868 0.291626 13.6849 1.47444 13.6849 2.9285C13.6849 4.38256 14.8677 5.56506 16.3218 5.56506ZM16.3218 0.877563C16.5911 0.877563 16.8578 0.930613 17.1066 1.03368C17.3554 1.13675 17.5815 1.28782 17.772 1.47827C17.9624 1.66872 18.1135 1.89481 18.2166 2.14364C18.3196 2.39247 18.3727 2.65917 18.3727 2.9285C18.3727 3.19783 18.3196 3.46453 18.2166 3.71336C18.1135 3.96219 17.9624 4.18829 17.772 4.37873C17.5815 4.56918 17.3554 4.72025 17.1066 4.82332C16.8578 4.92639 16.5911 4.97944 16.3218 4.97944C15.7778 4.97944 15.2561 4.76336 14.8715 4.37873C14.4869 3.99411 14.2708 3.47244 14.2708 2.9285C14.2708 2.38456 14.4869 1.86289 14.8715 1.47827C15.2561 1.09364 15.7778 0.877563 16.3218 0.877563ZM3.138 2.63538H5.05331C5.15608 2.81349 5.30392 2.96142 5.48198 3.06427C5.66005 3.16713 5.86205 3.22129 6.06769 3.22131H7.23956C7.8855 3.22131 8.41144 2.69538 8.41144 2.04944C8.41144 1.4035 7.8855 0.877563 7.23956 0.877563H7.08206C6.9793 0.699447 6.83145 0.551524 6.65339 0.448668C6.47533 0.345813 6.27332 0.29165 6.06769 0.291626H3.138C2.49206 0.291626 1.96613 0.817564 1.96613 1.4635C1.96613 2.10944 2.49206 2.63538 3.138 2.63538ZM3.138 0.877563H6.06769C6.39081 0.877563 6.65363 1.14006 6.65363 1.4635H7.23956C7.56269 1.4635 7.8255 1.726 7.8255 2.04944C7.8255 2.37288 7.56269 2.63538 7.23956 2.63538H6.06769C5.91229 2.63538 5.76325 2.57364 5.65337 2.46376C5.54348 2.35387 5.48175 2.20484 5.48175 2.04944H3.138C2.9826 2.04944 2.83356 1.98771 2.72368 1.87782C2.6138 1.76794 2.55206 1.6189 2.55206 1.4635C2.55206 1.3081 2.6138 1.15907 2.72368 1.04918C2.83356 0.939296 2.9826 0.877563 3.138 0.877563ZM10.1693 4.10038H11.3411C11.9871 4.10038 12.513 3.57444 12.513 2.9285C12.513 2.28256 11.9871 1.75663 11.3411 1.75663H10.1693C9.52331 1.75663 8.99738 2.28256 8.99738 2.9285C8.99738 3.57444 9.52331 4.10038 10.1693 4.10038ZM10.1693 2.34256H11.3411C11.6643 2.34256 11.9271 2.60506 11.9271 2.9285C11.9271 3.25194 11.6643 3.51444 11.3411 3.51444H10.1693C10.0139 3.51444 9.86481 3.45271 9.75493 3.34282C9.64505 3.23294 9.58331 3.0839 9.58331 2.9285C9.58331 2.7731 9.64505 2.62407 9.75493 2.51418C9.86481 2.4043 10.0139 2.34256 10.1693 2.34256ZM5.18894 3.80725H4.01706C3.37113 3.80725 2.84519 4.33319 2.84519 4.97913C2.84519 5.62506 3.37113 6.151 4.01706 6.151H5.18894C5.83488 6.151 6.36081 5.62506 6.36081 4.97913C6.36081 4.33319 5.83488 3.80725 5.18894 3.80725ZM5.18894 5.56506H4.01706C3.86166 5.56506 3.71263 5.50333 3.60274 5.39345C3.49286 5.28356 3.43113 5.13453 3.43113 4.97913C3.43113 4.82373 3.49286 4.67469 3.60274 4.56481C3.71263 4.45492 3.86166 4.39319 4.01706 4.39319H5.18894C5.51206 4.39319 5.77488 4.65569 5.77488 4.97913C5.77488 5.30256 5.51206 5.56506 5.18894 5.56506ZM14.1468 11.2213C14.3143 11.2532 14.4058 11.2041 14.6464 11.0576C14.9786 10.8538 15.4355 10.5744 16.1874 10.7185L16.2877 10.7376C16.6724 8.73288 13.4814 7.49381 13.3321 7.44881C13.4814 8.29288 13.7092 9.67756 13.8596 11.0338C13.9536 11.1469 14.023 11.1979 14.1468 11.2213ZM10.1018 10.1888C10.2602 10.4113 10.3236 10.4901 10.4858 10.521C10.6468 10.5523 10.7352 10.5023 10.9677 10.3548C10.9861 10.3429 11.0064 10.3307 11.0249 10.3182C11.6458 9.16538 12.3249 8.03288 12.753 7.33788C12.5499 7.31194 9.16238 7.31788 8.76019 9.30131L8.85831 9.32038C9.57863 9.45756 9.88081 9.88006 10.1018 10.1888Z"
                          fill={selected ? "#feb20e" : "#3A4856"}
                        />
                        <path
                          d="M17.6868 9.66664C17.1608 7.7282 14.7324 6.7357 14.3621 6.59539C13.8493 6.32852 12.9189 6.17352 12.4218 6.15102C10.9568 6.08445 7.85394 6.30383 7.31363 9.03539L7.26863 9.26445L7.26519 9.27977L7.26331 9.29602C7.24619 9.41877 7.2397 9.54277 7.24394 9.66664H0.208313V19.0416H18.9583V9.66664H17.6868ZM7.84394 9.37695L7.88863 9.14914C8.343 6.85164 11.1396 6.67508 12.4221 6.73695C12.858 6.75789 13.6886 6.8957 14.1217 7.13102C14.1217 7.13102 17.6505 8.40289 17.1524 10.9204L17.1077 11.1479C17.0243 11.4729 16.9058 11.6451 16.7908 11.6451C16.713 11.6451 16.6374 11.5657 16.5755 11.402L16.3549 11.3598C16.2454 11.3383 16.1342 11.3272 16.0227 11.3266C15.2927 11.3266 15.0246 11.8579 14.4249 11.8579C14.3586 11.8579 14.288 11.8513 14.2124 11.837C13.3596 11.6741 13.4971 10.8135 12.4083 10.6051C12.2997 10.5838 12.1893 10.5728 12.0786 10.5723C11.348 10.5723 11.0799 11.1041 10.4796 11.1041C10.4136 11.1041 10.343 11.0976 10.2674 11.0835C9.41456 10.9201 9.55175 10.0595 8.46362 9.85133L8.24144 9.80914C8.14394 9.91383 8.05988 9.96352 7.99269 9.96352C7.8555 9.96258 7.79144 9.75195 7.84394 9.37695ZM12.5771 11.2713L11.6683 15.8716C11.6532 15.9487 11.6083 16.0167 11.5434 16.0608C11.4784 16.1048 11.3986 16.1214 11.3214 16.107C11.2834 16.0998 11.2471 16.0851 11.2147 16.0638C11.1824 16.0425 11.1546 16.0149 11.133 15.9827C11.1114 15.9506 11.0964 15.9144 11.0889 15.8764C11.0814 15.8384 11.0815 15.7993 11.0893 15.7613L11.9967 11.166L12.5771 11.2713ZM18.3724 18.4557H4.82206C-1.06512 13.9063 5.68644 12.2979 11.5864 11.7307L10.8018 15.7041C10.7708 15.8585 10.8024 16.016 10.8902 16.1466C10.9436 16.2265 11.016 16.2919 11.101 16.337C11.1859 16.382 11.2806 16.4053 11.3767 16.4048C11.658 16.4048 11.9017 16.2041 11.9561 15.9279L12.8055 11.627L12.9514 11.6163C12.9599 11.6276 12.9686 11.6373 12.9774 11.6488C13.193 11.9213 13.4883 12.2948 14.103 12.412C14.2118 12.4326 14.3202 12.4435 14.4252 12.4435C14.8661 12.4435 15.1799 12.2645 15.4318 12.1204C15.643 11.9991 15.7958 11.9123 16.0233 11.9123C16.0789 11.9123 16.1386 11.9173 16.2018 11.9276C16.4114 12.1954 16.6699 12.231 16.7914 12.231C17.0671 12.231 17.4261 12.0813 17.6336 11.4273C18.1002 11.4232 18.3727 11.426 18.3727 11.426L18.3724 18.4557Z"
                          fill={selected ? "#feb20e" : "#3A4856"}
                        />
                      </svg>
                      Tours
                    </button>
                  )}
                </Tab>
                <Tab as={Fragment}>
                  {({ selected }) => (
                    <button
                      className={`${style.tab_btn}  ${
                        selected ? style.selected : ""
                      }`}
                    >
                      <svg
                        width="14"
                        height="17"
                        viewBox="0 0 14 17"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M0.916687 11.6667H3.41669V16.6667H0.916687V11.6667ZM13.4167 0.325C13.35 1.55 13.0417 2.60833 12.4667 3.50833C11.8917 4.40833 11.1 5 10.0834 5.325V16.6667H8.41669V11.6667H6.75002V16.6667H5.08335V6.73333C4.85002 6.80833 4.66669 6.9 4.57502 7.00833C3.79169 7.63333 3.41669 8.49167 3.41669 9.58333V10H1.75002V9.58333C1.75002 7.94167 2.35002 6.61667 3.52502 5.6C4.69169 4.63333 6.05002 4.16667 7.58335 4.16667C8.75835 4.16667 9.71669 3.86667 10.475 3.29167C11.3334 2.59167 11.75 1.625 11.75 0.416667V0H13.4167V0.325ZM7.58335 0C8.02538 0 8.4493 0.175595 8.76186 0.488155C9.07442 0.800716 9.25002 1.22464 9.25002 1.66667C9.25002 2.10869 9.07442 2.53262 8.76186 2.84518C8.4493 3.15774 8.02538 3.33333 7.58335 3.33333C7.14133 3.33333 6.7174 3.15774 6.40484 2.84518C6.09228 2.53262 5.91669 2.10869 5.91669 1.66667C5.91669 1.22464 6.09228 0.800716 6.40484 0.488155C6.7174 0.175595 7.14133 0 7.58335 0Z"
                          fill={selected ? "#feb20e" : "#3A4856"}
                        />
                      </svg>
                      Cars
                    </button>
                  )}
                </Tab>
              </Tab.List>

              <Tab.Panels className={style.searchtab_panel}>
                <Tab.Panel>
                  <FlightSearchCard />
                </Tab.Panel>
                <Tab.Panel>
                  <HotelSearchCard />
                </Tab.Panel>
                <Tab.Panel>
                  <TourSearchCard />
                </Tab.Panel>
                <Tab.Panel>
                  <TourSearchCard />
                </Tab.Panel>
              </Tab.Panels>
            </Tab.Group>
          </div>
        </section>
        {/* Hot Deals */}
        <section>
          <div className="container">
            <SectionTitle>Exclusive Offers</SectionTitle>
            <div className="grid  grid-cols-xl-2 grid-cols-lg-2 grid-cols-1  gap-xl_2 gap-lg_2 gapX_1">
              <HotDealsCard />
              <HotDealsCard />
            </div>
          </div>
        </section>

        {/* Popular Destinations*/}
        <section>
          <div className="container">
            <SectionTitle>Popular Destinations</SectionTitle>
            <div className="grid   grid-cols-xl-3  grid-cols-lg-2 grid-cols-1 gap-xl_2 gap-lg_2 gapX_1">
              <div className="col-span-2">
                <HomePreviewCard />
              </div>
              <HomePreviewCard />
              <HomePreviewCard />
              <HomePreviewCard />
              <HomePreviewCard />
            </div>
          </div>
        </section>
        {/* Popular Tours*/}
        <section>
          <div className="container">
            <SectionTitle>Popular Hotels</SectionTitle>
            <div className="grid   grid-cols-xl-4 grid-cols-lg-2 grid-cols-1 gap-xl_2 gap-lg_2 gapX_1 ">
              <div className="col-span-2">
                <HotelPreviewCard />
              </div>
              <HotelPreviewCard />
              <HotelPreviewCard />
            </div>
          </div>
        </section>
        {/* Popular Tours*/}
        <section>
          <div className="container">
            <SectionTitle>Popular Tours</SectionTitle>

            <div className="tour_swiper__box">
              {domLoaded && (
                <Swiper
                  navigation={{
                    nextEl: ".banner-swiper-button-next",
                    prevEl: ".banner-swiper-button-prev",
                  }}
                  modules={[Navigation]}
                  freeMode={true}
                  loop={true}
                  className="tour_swiper"
                  spaceBetween={20}
                  breakpoints={{
                    592: {
                      slidesPerView: 1,
                      spaceBetween: 20,
                    },
                    768: {
                      slidesPerView: 1,
                      spaceBetween: 40,
                    },
                    992: {
                      slidesPerView: 2,
                      spaceBetween: 40,
                    },
                    1024: {
                      slidesPerView: 3,
                      spaceBetween: 50,
                    },
                  }}
                >
                  {[...new Array(5)].map((_, i) => (
                    <SwiperSlide key={i}>
                      <TourPreviewCard />
                    </SwiperSlide>
                  ))}
                </Swiper>
              )}
              <div className="tour_swiper__navigation">
                <button className="banner-swiper-button-prev banner-navigation-btn">
                  <Image src={images["arrow_left_line.svg"]} alt="arrow left" />
                </button>
                <button className="banner-swiper-button-next banner-navigation-btn">
                  <Image
                    src={images["arrow_right_line.svg"]}
                    alt="arrow right"
                  />
                </button>
              </div>
            </div>
          </div>
        </section>

        <section className={`${style.prefooter} mt-5 text-center`}>
          <div className="container">
            <h3 className="text-white uppercase semibold">
              Save time, Save money!
            </h3>
            <p className="text-white ">
              Sign up and we’ll send the best deals to you{" "}
            </p>
            <div
              className={`grid grid-cols-xl-4 grid-cols-lg-4 grid-cols-md-4 grid-cols-1  w-100 m-auto gap-2 ${style.prefooter__inner}`}
            >
              <div className="col-span-3">
                <input
                  placeholder="Email"
                  className="form-control w-100 py-2"
                />
              </div>
              <div className="btn btn-warning text-white semibold  w-50  mx-auto">
                Sign Up
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};

export default Home;
